on:
  push:
  pull_request:

name: CI

jobs:
  check:
    name: Check
    runs-on: ubuntu-20.04
    steps:
      - run: sudo apt-get install libv4l-dev
      - uses: actions/checkout@v4
      - name: Check `v4l2`
        run: cargo check --workspace --all-targets
      - name: Check `libv4l`
        run: cargo check --workspace --all-targets --no-default-features --features libv4l

  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - run: sudo apt-get install libv4l-dev
      - uses: actions/checkout@v4
      - name: Test all targets
        run: cargo test --workspace --all-targets
      - name: Test docs
        run: cargo test --workspace --doc

  fmt:
    name: Rustfmt
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-20.04
    steps:
      - run: sudo apt-get install libv4l-dev
      - uses: actions/checkout@v4
      - name: Clippy lint `v4l2`
        run: cargo clippy --workspace --all-targets -- -D warnings
      - name: Clippy lint `libv4l`
        run: cargo clippy --workspace --all-targets --no-default-features --features libv4l -- -D warnings

  docs:
    name: Build-test docs
    runs-on: ubuntu-20.04
    steps:
      - run: sudo apt-get install libv4l-dev
      - uses: actions/checkout@v4
      - name: Document all crates
        env:
          RUSTDOCFLAGS: -Dwarnings
        run: cargo doc --workspace --no-deps --document-private-items
